server:
  port: 8080

messaging-config:
  topics:
    -
      name: input.topic
    -
      name: output.topic
    -
      name: output.topic.dev
    -
      name: output.topic.lt


spring:
  kafka:
    streams:
      security:
        protocol: SSL
      bootstrap-servers:
        - 192.168.18.122:9094
      application-id: template-kafka-stream
      cache-max-size-buffering: 1048576
      cleanup.on-shutdown: false
      properties:
        ssl.endpoint.identification.algorithm:
        group-id: ks-poc-kafka-stream
        replication: 1
        max:
          poll:
            records: 50
        commit:
          interval:
            ms: 100
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serde
          value:
            serde: org.apache.kafka.common.serialization.Serde
  output:
    ansi:
      enabled: always
  cloud:
    kubernetes:
      enabled: false
  application:
    name: ks-poc-kafka-streams
  profiles:
    active: local